<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Dynamic.Employees.Application\Dynamic.Employees.Application.csproj" />
    <ProjectReference Include="..\Dynamic.Employees.Data.PostgreSql\Dynamic.Employees.Data.PostgreSql.csproj" />
    <ProjectReference Include="..\Dynamic.Employees.Data.SqlServer\Dynamic.Employees.Data.SqlServer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Dynamic.Json.AspNetCore" Version="0.3.0-preview.1" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="EmployeeApi.UnitTests" />
  </ItemGroup>
</Project>
