// <auto-generated />
using System;
using Dynamic.Employees.Data.PostgreSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dynamic.Employees.Data.PostgreSql.Migrations
{
    [DbContext(typeof(PostgreSqlEmployeeDbContext))]
    partial class PostgreSqlEmployeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dynamic.Employees.Domain.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("EmployeeTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("FieldValues")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("FieldValuesJson");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeTypeId");

                    b.HasIndex("FirstName");

                    b.HasIndex("LastName");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("Dynamic.Employees.Domain.Models.EmployeeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("EmployeeType", (string)null);
                });

            modelBuilder.Entity("Dynamic.Employees.Domain.Models.Employee", b =>
                {
                    b.HasOne("Dynamic.Employees.Domain.Models.EmployeeType", "EmployeeType")
                        .WithMany()
                        .HasForeignKey("EmployeeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmployeeType");
                });

            modelBuilder.Entity("Dynamic.Employees.Domain.Models.EmployeeType", b =>
                {
                    b.OwnsMany("Dynamic.Employees.Domain.Models.EmployeeTypeField", "Fields", b1 =>
                        {
                            b1.Property<Guid>("EmployeeTypeId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("FieldType");

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Label")
                                .IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<int>("Order");

                            b1.Property<bool>("Required");

                            b1.HasKey("EmployeeTypeId", "__synthesizedOrdinal");

                            b1.ToTable("EmployeeType");

                            b1
                                .ToJson("FieldsJson")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeTypeId");

                            b1.OwnsMany("Dynamic.Employees.Domain.Models.FieldOption", "Options", b2 =>
                                {
                                    b2.Property<Guid>("EmployeeTypeFieldEmployeeTypeId");

                                    b2.Property<int>("EmployeeTypeField__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Label")
                                        .IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired();

                                    b2.HasKey("EmployeeTypeFieldEmployeeTypeId", "EmployeeTypeField__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("EmployeeType");

                                    b2.WithOwner()
                                        .HasForeignKey("EmployeeTypeFieldEmployeeTypeId", "EmployeeTypeField__synthesizedOrdinal");
                                });

                            b1.Navigation("Options");
                        });

                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
